#!/usr/bin/env python3
"""Pilot: Luna episodes against the Opus reference, by measures/pilot-protocol.md.

  compare_pilot.py REFERENCE.json PREFIX NAME
      REFERENCE: JSON array of reference episodes. PREFIX: Luna agent id prefix (e.g. pilot).
      Writes measures/NAME.md and measures/NAME.json.
"""
import glob, json, os, statistics, sys

RUN = '/Users/ruliny/.claude/plugins/data/entrust-nowely/orchestrate/-Users-ruliny-Git-agent-skills/2026-09-26-writing-replication'
RESEARCH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def match(a, b):
    if a['user_turn'] != b['user_turn']:
        return False
    return a['draft_turn'] == b['draft_turn'] or a.get('draft_missing') or b.get('draft_missing')


def dedup(eps):
    seen, out = set(), []
    for e in eps:
        k = (e['user_turn'], e['draft_turn'])
        if k not in seen:
            seen.add(k)
            out.append(e)
    return out


def metrics(ref, luna):
    G = [r for r in ref if r['confidence'] == 'high']
    matched_G = [g for g in G if any(match(g, l) for l in luna)]
    extra = [l for l in luna if not any(match(l, r) for r in ref)]
    return dict(G=len(G), matched_G=len(matched_G), recall=round(len(matched_G) / len(G), 3) if G else None,
                luna=len(luna), extra=len(extra), extra_share=round(len(extra) / len(luna), 3) if luna else None,
                missed=[g['id'] for g in G if g not in matched_G], extra_ids=[l['id'] for l in extra])


def main(ref_path, prefix, name):
    ref = json.load(open(ref_path))
    parts = sorted({r['id'].split('-')[1] for r in ref})
    runs, eps = [], {'A': [], 'B': []}
    for p in sorted(glob.glob(f'{RUN}/{prefix}-P*-[AB]/report.json')):
        aid = p.split('/')[-2]
        if aid.split('-')[1] not in parts:
            continue
        d = json.load(open(p))
        aj = d.get('answerJson') or {}
        angle = aid[-1]
        e = aj.get('episodes') or []
        eps[angle] += e
        runs.append(dict(id=aid, tokens=(d.get('tokenUsage') or {}).get('total', {}).get('totalTokens', 0),
                         episodes=len(e), exit=d.get('exitCode'), wall=round((d.get('timing') or {}).get('wallMs', 0) / 1000)))
    parts_seen = sorted({r['id'].split('-')[1] for r in runs})
    ref = [r for r in ref if r['id'].split('-')[1] in parts_seen]
    res = {}
    for label, luna in [('overall', dedup(eps['A'] + eps['B'])),
                        ('overall_no_low', dedup([e for e in eps['A'] + eps['B'] if e['confidence'] != 'low'])),
                        ('angle_A', dedup(eps['A'])), ('angle_B', dedup(eps['B']))]:
        r = ref if label.startswith('overall') else [x for x in ref if x['angle'] == label[-1]]
        res[label] = metrics(r, luna)
    toks = [r['tokens'] for r in runs]
    res['runs'] = runs
    res['tokens'] = dict(n=len(toks), total=sum(toks), median=int(statistics.median(toks)) if toks else 0, max=max(toks) if toks else 0)
    ov = res['overall']
    res['gates'] = dict(recall_ok=ov['recall'] is not None and ov['recall'] >= 5 / 6,
                        extra_ok=ov['extra_share'] is not None and ov['extra_share'] <= 0.20)
    json.dump(res, open(f'{RESEARCH}/measures/{name}.json', 'w'), ensure_ascii=False, indent=1)
    lines = [f'# {name}', '', f'Reference: {ref_path} ({len(ref)} episodes on parts {", ".join(parts_seen)}); Luna prefix: {prefix}.',
             'Rules: measures/pilot-protocol.md. Generated by tools/compare_pilot.py.', '',
             '| set | G (ref high) | matched G | recall | Luna episodes | extra | extra share |', '| --- | --- | --- | --- | --- | --- | --- |']
    for k in ('overall', 'overall_no_low', 'angle_A', 'angle_B'):
        m = res[k]
        lines.append(f"| {k} | {m['G']} | {m['matched_G']} | {m['recall']} | {m['luna']} | {m['extra']} | {m['extra_share']} |")
    lines += ['', f"Gates (overall, low included): recall >= 5/6 -> {res['gates']['recall_ok']}; extra <= 20 % -> {res['gates']['extra_ok']}",
              '', f"Tokens per Luna run: n={res['tokens']['n']}, total={res['tokens']['total']:,}, median={res['tokens']['median']:,}, max={res['tokens']['max']:,}",
              '', f"Missed confident reference episodes: {', '.join(ov['missed']) or 'none'}",
              f"Extra Luna episodes: {', '.join(ov['extra_ids']) or 'none'}", '',
              '| run | exit | episodes | tokens | wall s |', '| --- | --- | --- | --- | --- |']
    lines += [f"| {r['id']} | {r['exit']} | {r['episodes']} | {r['tokens']:,} | {r['wall']} |" for r in runs]
    open(f'{RESEARCH}/measures/{name}.md', 'w').write('\n'.join(lines) + '\n')
    print('\n'.join(lines[5:12]))


if __name__ == '__main__':
    main(*sys.argv[1:4])
