#!/usr/bin/env python3
"""Stress-test results per principle.

  stress_summary.py PRINCIPLES.json
      reads every st-* and cx-* report of the run (only agents listed in briefs/stress-*.new.tsv, taking the latest
      relaunch -rN of each), checks each quote against corpus/turns.jsonl (exact substring), and writes
      stress/pairs-verdicts.json, stress/cx-findings.json and stress/summary.md
"""
import json, os, re, sys, collections

RUN = '~/.claude/plugins/data/entrust-nowely/orchestrate/-Users-user-Git-agent-skills/2026-09-26-writing-replication'
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def latest(ids):
    """id -> the id of its latest relaunch that has a report (id, id-r1, id-r2)."""
    out = {}
    for i in ids:
        best = i
        for k in (1, 2, 3):
            if os.path.exists(f'{RUN}/{i}-r{k}/report.json'):
                best = f'{i}-r{k}'
        out[i] = best
    return out


def load(i):
    try:
        return json.load(open(f'{RUN}/{i}/report.json'))
    except Exception:
        return None


def main(ppath):
    P = {p['id']: p for p in json.load(open(ppath))}
    T = {t['id']: t['text'] for t in map(json.loads, open(f'{R}/corpus/turns.jsonl'))}
    ok = lambda turn, q: bool(q) and turn in T and q in T[turn]
    pairs_ids = [l.split('\t')[0] for l in open(f'{R}/briefs/stress-pairs.new.tsv') if l.strip()]
    cx_ids = [l.split('\t')[0] for l in open(f'{R}/briefs/stress-cx.new.tsv') if l.strip()]
    pairs, cx, missing = [], [], []
    for base, aid in latest(pairs_ids).items():
        d = load(aid)
        a = (d or {}).get('answerJson') or {}
        if not a:
            missing.append(aid)
            continue
        pairs.append(dict(agent=aid, principle=a.get('principle_id'), episode=a.get('episode_id'), verdict=a.get('verdict'),
                          quote=a.get('quote'), quote_turn=a.get('quote_turn'), quote_ok=ok(a.get('quote_turn'), a.get('quote')),
                          reason=a.get('reason'), tokens=d['tokenUsage']['total']['totalTokens']))
    for base, aid in latest(cx_ids).items():
        d = load(aid)
        a = (d or {}).get('answerJson') or {}
        if not a:
            missing.append(aid)
            continue
        for f in a.get('findings') or []:
            cx.append(dict(agent=aid, part=base.split('-', 1)[1], **f, user_quote_ok=ok(f.get('user_turn'), f.get('user_quote')),
                           draft_quote_ok=(not f.get('draft_quote')) or ok(f.get('draft_turn'), f.get('draft_quote'))))
    os.makedirs(f'{R}/stress', exist_ok=True)
    json.dump(pairs, open(f'{R}/stress/pairs-verdicts.json', 'w'), ensure_ascii=False, indent=1)
    json.dump(cx, open(f'{R}/stress/cx-findings.json', 'w'), ensure_ascii=False, indent=1)
    L = ['# Stress test per principle', '', 'Generated by tools/stress_summary.py from the st-* (principle x episode) and cx-* (counterexample search per part) reports.',
         f'Pairs: {len(pairs)} verdicts. Counterexample findings: {len(cx)} from {len(cx_ids)} parts. Agents without an answer: {len(missing)} {missing[:10]}.',
         'Quotes are checked as exact substrings of the named turn; a finding whose user quote fails is listed but marked `quote fails`.', '']
    pv = collections.defaultdict(collections.Counter)
    for x in pairs:
        pv[x['principle']][x['verdict']] += 1
    cv = collections.defaultdict(list)
    for x in cx:
        cv[x['principle_id']].append(x)
    L += ['| principle | strength | dialogs | pairs: supports / contradicts / out_of_scope / insufficient | cx: contradicts / narrows_scope / supports_new (quote ok) |',
          '| --- | --- | --- | --- | --- |']
    for pid, p in P.items():
        c = pv[pid]
        k = collections.Counter((f['verdict'], f['user_quote_ok']) for f in cv[pid])
        cxs = ' / '.join(f"{k[(v, True)]}" + (f" (+{k[(v, False)]} bad quote)" if k[(v, False)] else '') for v in ('contradicts', 'narrows_scope', 'supports_new'))
        L.append(f"| {pid} | {p.get('strength')} | {p.get('independent_dialogs')} | {c['supports']} / {c['contradicts']} / {c['out_of_scope']} / {c['insufficient_data']} | {cxs} |")
    L += ['', '## Details per principle', '']
    for pid, p in P.items():
        L += [f"### {pid} — {p['statement']}", '']
        for x in [x for x in pairs if x['principle'] == pid and x['verdict'] != 'supports']:
            L.append(f"- pair {x['episode']}: **{x['verdict']}** — {x['reason']} (quote {x['quote_turn']}: “{(x['quote'] or '')[:160]}”{'' if x['quote_ok'] else ' — quote fails'})")
        for f in cv[pid]:
            if f['verdict'] == 'supports_new':
                continue
            L.append(f"- cx {f['part']} {f['user_turn']}: **{f['verdict']}** — {f['reason']} (“{f['user_quote'][:160]}”{'' if f['user_quote_ok'] else ' — quote fails'})")
        new = [f for f in cv[pid] if f['verdict'] == 'supports_new']
        if new:
            L.append(f"- cx supports_new: {len(new)} ({sum(f['user_quote_ok'] for f in new)} with a verified quote): " + ', '.join(sorted({f['user_turn'] for f in new})))
        L.append('')
    unknown = [f for f in cx if f['principle_id'] not in P]
    if unknown:
        L += [f'Findings naming no known principle: {len(unknown)}', '']
    open(f'{R}/stress/summary.md', 'w').write('\n'.join(L) + '\n')
    print('\n'.join(L[:6]))
    tot = collections.Counter(x['verdict'] for x in pairs)
    print('pairs', dict(tot), 'cx', dict(collections.Counter(x['verdict'] for x in cx)))


if __name__ == '__main__':
    main(sys.argv[1])
