#!/usr/bin/env python3
"""Token totals of every Codex agent in the run, by role (agent id up to its first '-').

  tokens.py            prints the table and writes measures/tokens.md
"""
import glob, json, os, statistics

RUN = '/Users/ruliny/.claude/plugins/data/entrust-nowely/orchestrate/-Users-ruliny-Git-agent-skills/2026-09-26-writing-replication'
RESEARCH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

rows = []
for p in sorted(glob.glob(f'{RUN}/*/report.json')):
    aid = p.split('/')[-2]
    try:
        d = json.load(open(p))
    except Exception:
        continue
    tu = (d.get('tokenUsage') or {}).get('total') or {}
    rl = ((d.get('rateLimits') or {}).get('primary') or {})
    rows.append(dict(id=aid, role=aid.split('-')[0], model=d.get('model'), effort=d.get('effort') or d.get('reasoningEffort'),
                     total=tu.get('totalTokens', 0), cached=tu.get('cachedInputTokens', 0), out=tu.get('outputTokens', 0),
                     used=rl.get('usedPercent'), wall=round(((d.get('timing') or {}).get('wallMs') or 0) / 1000)))

by = {}
for r in rows:
    by.setdefault(r['role'], []).append(r)
lines = ['| role | runs | total tokens | cached input | output | median/run | max/run |', '| --- | --- | --- | --- | --- | --- | --- |']
for role, rs in sorted(by.items()):
    t = [r['total'] for r in rs]
    lines.append(f"| {role} | {len(rs)} | {sum(t):,} | {sum(r['cached'] for r in rs):,} | {sum(r['out'] for r in rs):,} | {int(statistics.median(t)):,} | {max(t):,} |")
T = sum(r['total'] for r in rows)
lines.append(f"| **all** | {len(rows)} | {T:,} | {sum(r['cached'] for r in rows):,} | {sum(r['out'] for r in rows):,} | | |")
used = [r['used'] for r in rows if r['used'] is not None]
lines.append(f"\nQuota (weekly, primary window): max usedPercent seen = {max(used) if used else 'n/a'}")
text = '# Codex tokens by role\n\nSource: tokenUsage.total in every report.json of the run; generated by tools/tokens.py.\n\n' + '\n'.join(lines) + '\n\n## Per agent\n\n| id | model | effort | total | cached | used% | wall s |\n| --- | --- | --- | --- | --- | --- | --- |\n' + '\n'.join(
    f"| {r['id']} | {r['model']} | {r['effort']} | {r['total']:,} | {r['cached']:,} | {r['used']} | {r['wall']} |" for r in rows) + '\n'
os.makedirs(f'{RESEARCH}/measures', exist_ok=True)
open(f'{RESEARCH}/measures/tokens.md', 'w').write(text)
print('\n'.join(lines))
