const fs = require('node:fs');
const cp = require('node:child_process');
const path = require('node:path');
const root = path.resolve(__dirname, '../../../..');
const out = __dirname;
const designDir = path.join(require('node:os').tmpdir(), 'tmp.iUPMIn91WR');
const round = path.join(root,'research/2026-09-11-markup-round-0');
const ABS=/\b(every|always|never|cannot|guarantees?|ensures?|nothing|only|by default)\b/i;
const LIFE=/\b(stays?|removed?|removes?|continu\w*|resum\w*|reclaim\w*|ke(ep|pt)s?|prun\w*|until|left|lasts?|clears?|age out|trimmed|deletes?|preserved|goes when|ends|killed|dies|crashed|dead)\b/i;
const quotes=fs.readFileSync(path.join(designDir,'q.txt'),'utf8').trim().split('\n').map(s=>{const i=s.indexOf('|');const id=s.slice(0,i), t=s.slice(i+1).replace(/read-only/gi,'readonly'); return {id,abs:ABS.test(t),life:LIFE.test(t)};});
const edits=JSON.parse(fs.readFileSync(path.join(round,'edits/08.json'),'utf8'));
const orig=fs.readFileSync(path.join(round,'00-draft.md'),'utf8');
const prev=fs.readFileSync(path.join(round,'07-lifecycle.md'),'utf8');
const caught=[['R08-1',0],['R08-4',10],['R08-5',11],['R08-6',13],['R08-8',16],['R08-10',26]];
const missed=[['R08-2',6],['R08-3',7],['R08-7',14],['R08-9',24]];
const log=[];
function say(s){log.push(s);}
say('Checks executed in this turn; no repository test suite or live behavior probe was run.');
say('Trigger recount with the exact JavaScript regexes and stated read-only mask: total='+quotes.length+' ABS='+quotes.filter(x=>x.abs).length+' LIFE='+quotes.filter(x=>x.life).length+' either='+quotes.filter(x=>x.abs||x.life).length+'.');
say('Trigger misses: '+quotes.filter(x=>!x.abs&&!x.life).map(x=>x.id).join(', ')+'.');
say('R07-3 quote: '+fs.readFileSync(path.join(designDir,'q.txt'),'utf8').split('\n').find(x=>x.startsWith('R07-3|')));
const appendix=cp.spawnSync('node',[path.join(designDir,'gateload.mjs'),round],{encoding:'utf8'});
say('Command: node '+path.join(designDir,'gateload.mjs')+' '+round+' — started; exit '+appendix.status+'; exact diagnostic follows:');
say(appendix.stderr.trim());
const corrected=cp.spawnSync('node',[path.join(out,'gateload.cjs'),round],{encoding:'utf8'});
say('Unchanged .cjs copy command started; exit '+corrected.status+'; gate-load output follows:');say(corrected.stdout.trim());
say('HO2 base check: edits/08.json[0].old occurs '+(orig.split(edits[0].old).length-1)+' times in 00-draft.md and '+(prev.split(edits[0].old).length-1)+' time in 07-lifecycle.md.');
const countOld = edits.map((e,i)=>[i,orig.split(e.old).length-1]);
say('HO2 first-round-original matches (zero-based index:count): '+countOld.map(x=>x.join(':')).join(', '));
const norm=t=>t.replace(/\s+/g,' ');
say('HO2 semantic-coupling check for lock edits [16] and [24]: old[16] in new[24]='+norm(edits[24].new).includes(norm(edits[16].old))+'; old[24] in new[16]='+norm(edits[16].new).includes(norm(edits[24].old))+'. Both are false although D1:447-448 identifies compound damage.');
const e6=JSON.parse(fs.readFileSync(path.join(round,'edits/06.json'),'utf8'));
say('R06-4 input is edits/06.json[8]; its new text has ABS='+ABS.test(e6[8].new)+' LIFE='+LIFE.test(e6[8].new)+'; contains behavioural assertion about a report path.');
say('G5 zero-baseline counterexample: if each planted paraphrase evades the regex, regex matches=0; reader matches=0 does not satisfy fewer-than-regex (0 < 0 is '+(0<0)+').');
const cfg=[{name:'returned retired falsehood',pattern:'false statement',want:false}];
fs.writeFileSync(path.join(out,'toy-ledger.json'),JSON.stringify(cfg));
['correct','false statement','correct','false statement'].forEach((s,i)=>fs.writeFileSync(path.join(out,'toy-round-'+i+'.md'),s));
const ledger=cp.spawnSync('node',[path.join(root,'plugins/terse/skills/rewrite/scripts/ledger.mjs'),path.join(out,'toy-ledger.json'),...[0,1,2,3].map(i=>path.join(out,'toy-round-'+i+'.md'))],{encoding:'utf8'});
say('G6 recurrence check: existing ledger command started; exit '+ledger.status+' (expected ledger refusal); output follows:');say(ledger.stdout.trim());
say('G6 proposed first-YES formula for round 3: first YES is at round 1, no positive rows exist, so computed regressions=0; the previously removed false sentence was reintroduced at round 3, so definition in rewrite/SKILL.md:117-118 counts 1.');
say('G6 persistent-error check: negative pattern present in rounds 1 and 2 gives failure count 1 on round 2 but first-YES formula 0; the two stated counts disagree.');
say('Blind refusal list caught '+caught.length+'/10 by edit and disputed proposition: '+caught.map(([id,i])=>id+' -> edits/08.json['+i+']').join('; ')+'.');
say('Blind refusal list missed '+missed.length+'/10: '+missed.map(([id,i])=>id+' -> edits/08.json['+i+']').join('; ')+'.');
say('R08-5 qualification: blind refusal challenged exclusivity as unsupported; it did not identify the decorrelated-model counterexample. Strict explicit-counterexample scoring is 5 caught / 5 missed, adding R08-5 to misses.');
say('Part 6 named desk subset: caught 5/7 by refusal, missed R08-2 and R08-9; strict explicit-counterexample scoring 4/7. This run is n=1 and was Astra, not the proposed Sol verifier.');
say('Additional refusal indices outside D1 ten: [1,3,12,18,20,25]. Not classified as false positives without an independent adjudication of those claims.');
fs.writeFileSync(path.join(out,'checks.log'),log.join('\n')+'\n');console.log(log.join('\n'));
